name: Build and Deploy
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v12
      with:
        version: 'latest'
        
    - name: Compile WASM
      run: |
        mkdir -p wasm
        emcc c_src/*.c -O3 \
          -s WASM=1 \
          -s MODULARIZE=1 \
          -s EXPORTED_RUNTIME_METHODS='["cwrap"]' \
          -s EXPORTED_FUNCTIONS='["_wave_sim"]' \
          -o wasm/wave_sim.js
          
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./